version: '3.8'

services:

  mysql-db:
    image: mysql:8.4
    container_name: mysql-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: dbNordSys
      MYSQL_USER: nordsys
      MYSQL_PASSWORD: 123456

    volumes:
      - ./mysql:/var/lib/mysql

    ports:
      - "3306:3306"